version: "3"

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: 

services:

  poll:
    build: ./poll
    restart: always
    ports:
      - "5000:80"
    links:
      - redis
      - db
    depends_on:
      - redis
    networks:
      - poll-tier
    environment:
      - 0.0.0.0

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier

  worker:
    build: ./worker
    restart: always
    depends_on:
      - db
      - redis
    networks:
      - back-tier
    environment:
      - 0.0.0.0

  db:
    image: postgres:13.0
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - "./schema.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - result-tier
      - back-tier
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"

  result:
    build: ./result
    restart: always
    depends_on: 
      - db
    ports:
      - "5001:80"
    networks:
      - result-tier
    environment:
      - 0.0.0.0